systems:
  basedir: "./results/tankandtemples"
  vis_every: 100000

model:
  model_name: "SynergyNeRF"
  N_voxel_init: 110592
  upsampling_type: unaligned
  upsample_list: [3500, 5000, 7000, 9000, 11000, 13000, 15000]
  # upsample_list: [3000, 6000, 9000]
  density_n_comp: [32, 32, 32]
  update_alpha_grid_mask_list: [2000, 4000]
  fusion_one: "multiply"
  fusion_two: "concat"
  init_scale: 0.1
  init_shift: 0.0
  density_dim: 1
  density_mode: "Grid_Coord_Mixing_MLP"
  TV_weight_density: 0.005

  alpha_mask_thres: 0.0001
  ray_march_weight_thres: 0.00001

  curriculum_num_modes : 3
  curriculum_num_features : 32
  curriculum_start : 0.1
  curriculum_end : 0.5

data:
  dataset_name: TanksAndTemple
  datadir: "./data/TanksAndTemple"
  scene: barn
  N_vis: 17
  scene_bbox_min: [-1.5, -1.5, -1.5]
  scene_bbox_max: [1.5, 1.5, 1.5]
  downsample: 0.5
  

optim:
  n_iters: 30000
  lr_decay_type: "exp"

render_val: True
render_test: True
render_path: True
expname: null