systems:
  basedir: "./results/SynergyNeRF/25_views"
  vis_every: 2000

model:
  model_name: "SynergyNeRF"
  N_voxel_init: 4096
  time_grid_init: 16
  time_grid_final: 24
  upsampling_type: unaligned
  upsample_list: [3000, 5000, 7000, 9000, 11000, 13000, 15000]
  update_alpha_grid_mask_list: [2000, 4000]
  fusion_one: "multiply"
  fusion_two: "concat"
  init_scale: 0.1
  init_shift: 0.0
  density_dim: 1
  density_mode: "Grid_Coord_Mixing_MLP"
  
  curriculum_num_modes : 3
  curriculum_num_features : 48
  curriculum_start : 0.0
  curriculum_end : 0.0

  TV_weight_density: 0.001
  TV_weight_app: 0.0001

data:
  datadir: "./data/D_nerf_synthetic"
  scene: "bouncingballs"
  scene_bbox_min: [-1.5, -1.5, -1.5]
  scene_bbox_max: [1.5, 1.5, 1.5]
  downsample: 1.0
  N_vis: 25

optim:
  n_iters: 30000
  lr_decay_type: "exp"

render_val: False
render_test: True
render_path: True
expname: null